/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.braveinnov.app

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class App {}

fun main(vararg args: String) {
    SpringApplication.run(App::class.java, *args)
}
